- name: start vsftpd
  service: name="{{vsftpd_service_name}}" state=started enabled=true
- name: stop vsftpd
  service: name="{{vsftpd_service_name}}" state=stopped 
- name: restart vsftpd 
  service: name="{{vsftpd_service_name}}" state=restart 
- name: enable vsftpd 
  service: name="{{vsftpd_service_name}}" enabled=true
- name: disable vsftpd 
  service: name="{{vsftpd_service_name}}" enabled=false
  
 

 
