- name: start apache
  service: name="{{apache_service_name}}" state=started enabled=true
- name: stop apache
  service: name="{{apache_service_name}}" state=stopped 
- name: restart apache 
  service: name="{{apache_service_name}}" state=restart 
- name: enable apache 
  service: name="{{apache_service_name}}" enabled=true
- name: disable apache 
  service: name="{{apache_service_name}}" enabled=false
  