- name: start ntp
  service: name="{{ntp_service_name}}" state=started enabled=true
- name: stop ntp
  service: name="{{ntp_service_name}}" state=stopped 
- name: restart ntp 
  service: name="{{ntp_service_name}}" state=restart 
- name: enable ntp 
  service: name="{{ntp_service_name}}" enabled=true
- name: disable ntp 
  service: name="{{ntp_service_name}}" enabled=false
  
 

 
