---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: amazon
    driver_config:
      image: phenompeople/amazonlinux-ccb:2016.09
      platform: centos
      privileged: true
      volume: /sys/fs/cgroup
      remove_images: false

  - name: centos-7.3
    driver_config:
      image: phenompeople/centos-ccb:7.3.1611
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume: /sys/fs/cgroup
      remove_images: true

  
  - name: centos-7.2
    driver_config:
      image: phenompeople/centos-ccb:7.2.1511
      platform: centos
      run_command: /usr/sbin/init
      privileged: true
      volume:
      - /sys/fs/cgroup
      remove_images: false

  - name: ubuntu14.04
    driver_config:
      image: phenompeople/ubuntu-ccb:14.04
      platform: ubuntu
      remove_images: true

  - name: ubuntu16.04
    driver_config:
      image: phenompeople/ubuntu-ccb:16.04
      platform: ubuntu
      remove_images: true
suites:
  - name: default
    run_list:
      - recipe[beats::filebeat_install]
      - recipe[beats::filebeat_service]
      - recipe[beats::filebeat_configure]
#      - recipe[beats::filebeat_uninstall]

    attributes:
      phenom:
        banner: 'Dont edit by Hand !!! This file is modified by Chef. Please contact admin.squad@phenompeople.com for further assitance'
      filebeat:
        logstash:
          array: "127.0.0.1:5044"
