name             'beats'
maintainer       'Phenompeople Pvt Ltd'
maintainer_email 'admin.squad@phenompeople.com'
license          'Apache 2.0'
description      'Installs/Configures beats'
long_description 'Installs/Configures beats'
version          '0.1.0'
