java_version: 8u121
java_version_ubuntu: 8u111
java_build_version_ubuntu: b14
java_build_version: b13
java_binary_version: "jre-{{java_version}}-linux-x64.tar.gz"
java_download_uri: "http://download.oracle.com/otn-pub/java/jdk/{{java_version}}-{{java_build_version}}/e9e7ea248e2c4826b92b3f075a80e441/{{java_binary_version}}"
java_base_directory: /usr/bin/java 
download_folder: /opt
java_app_dir: /opt/jre1.8.0_121
java_app_dir_bin: /opt/jre1.8.0_121/bin
java_download_uri_ubuntu: "http://download.oracle.com/otn/java/jdk/{{java_version_ubuntu}}-{{java_build_version_ubuntu}}/jdk-8u111-linux-x64.tar.gz"